//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type BlogPost struct {
	ID         int32 `sql:"primary_key"`
	CategoryID int32
	Title      string
	Slug       string
	Summary    *string
	Status     PostStatus
	Keywords   string
	Body       string
	AuthorID   int32
	CreatedAt  time.Time
	TenantID   int32
}
