//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type BlogComment struct {
	ID         int32 `sql:"primary_key"`
	AuthorID   int32
	BlogPostID int32
	Body       string
	CreatedAt  time.Time
}
