//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type BlogCommentLike struct {
	UserID    int32 `sql:"primary_key"`
	CommentID int32 `sql:"primary_key"`
	CreatedAt time.Time
}
