//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Invitation struct {
	ID             int32 `sql:"primary_key"`
	InviterID      int32
	InviteeEmail   string
	InvitationCode uuid.UUID
	Pending        bool
	CreatedAt      time.Time
	ExpiresAt      time.Time
	AcceptedAt     *time.Time
	TenantID       int32
}
