//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/PaluMacil/barkdognet/datastore/types"
	"time"
)

type OidcProvider struct {
	ID            int32 `sql:"primary_key"`
	DisplayName   string
	IssuerURL     string
	DiscoveryURL  string
	Scopes        types.TextArray
	ClientID      string
	ClientSecret  string
	RedirectURL   string
	AccessType    string
	AzureTenantID *string
	Active        bool
	CreatedAt     time.Time
	TenantID      int32
}
