//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PostStatus string

const (
	PostStatus_Draft     PostStatus = "draft"
	PostStatus_Published PostStatus = "published"
	PostStatus_Hidden    PostStatus = "hidden"
	PostStatus_Archived  PostStatus = "archived"
)

func (e *PostStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "draft":
		*e = PostStatus_Draft
	case "published":
		*e = PostStatus_Published
	case "hidden":
		*e = PostStatus_Hidden
	case "archived":
		*e = PostStatus_Archived
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PostStatus enum")
	}

	return nil
}

func (e PostStatus) String() string {
	return string(e)
}
