//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SysUser struct {
	ID                  int32 `sql:"primary_key"`
	Email               string
	EmailConfirmed      bool
	DisplayName         string
	GivenName           *string
	PhoneNumber         *string
	PhoneNumberVerified *bool
	FamilyName          *string
	Locked              bool
	PasswordHash        *[]byte
	LastLoginAt         *time.Time
	CreatedAt           *time.Time
}
