//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SysRole struct {
	ID          int32 `sql:"primary_key"`
	DisplayName string
	Description string
	CreatedAt   time.Time
	TenantID    int32
}
