//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SysTenant struct {
	ID           int32 `sql:"primary_key"`
	DisplayName  string
	APISubdomain string
	UIDomain     *string
	CreatedAt    time.Time
	Active       bool
}
