//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SysUser struct {
	ID                            int32 `sql:"primary_key"`
	Email                         string
	EmailVerified                 bool
	EmailVerificationHash         *[]byte
	EmailVerificationCodeIssuedAt *time.Time
	PasswordResetHash             *[]byte
	PasswordResetCodeIssuedAt     *time.Time
	DisplayName                   string
	GivenName                     string
	FamilyName                    string
	PhoneNumber                   *string
	PhoneNumberVerified           bool
	Location                      string
	Locked                        bool
	PasswordHash                  *[]byte
	LastLoginAt                   *time.Time
	CreatedAt                     time.Time
	Bio                           string
	SocialLinks                   string
}
