//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var PostStatus = &struct {
	Draft     postgres.StringExpression
	Published postgres.StringExpression
	Hidden    postgres.StringExpression
	Archived  postgres.StringExpression
}{
	Draft:     postgres.NewEnumValue("draft"),
	Published: postgres.NewEnumValue("published"),
	Hidden:    postgres.NewEnumValue("hidden"),
	Archived:  postgres.NewEnumValue("archived"),
}
