//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SysRole = newSysRoleTable("public", "sys_role", "")

type sysRoleTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	DisplayName postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SysRoleTable struct {
	sysRoleTable

	EXCLUDED sysRoleTable
}

// AS creates new SysRoleTable with assigned alias
func (a SysRoleTable) AS(alias string) *SysRoleTable {
	return newSysRoleTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SysRoleTable with assigned schema name
func (a SysRoleTable) FromSchema(schemaName string) *SysRoleTable {
	return newSysRoleTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SysRoleTable with assigned table prefix
func (a SysRoleTable) WithPrefix(prefix string) *SysRoleTable {
	return newSysRoleTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SysRoleTable with assigned table suffix
func (a SysRoleTable) WithSuffix(suffix string) *SysRoleTable {
	return newSysRoleTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSysRoleTable(schemaName, tableName, alias string) *SysRoleTable {
	return &SysRoleTable{
		sysRoleTable: newSysRoleTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newSysRoleTableImpl("", "excluded", ""),
	}
}

func newSysRoleTableImpl(schemaName, tableName, alias string) sysRoleTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		DisplayNameColumn = postgres.StringColumn("display_name")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		allColumns        = postgres.ColumnList{IDColumn, DisplayNameColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{IDColumn, DisplayNameColumn, CreatedAtColumn}
	)

	return sysRoleTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		DisplayName: DisplayNameColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
