//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	BlogCategory = BlogCategory.FromSchema(schema)
	BlogComment = BlogComment.FromSchema(schema)
	BlogCommentLike = BlogCommentLike.FromSchema(schema)
	BlogPost = BlogPost.FromSchema(schema)
	BlogPostLike = BlogPostLike.FromSchema(schema)
	BlogTag = BlogTag.FromSchema(schema)
	GooseDbVersion = GooseDbVersion.FromSchema(schema)
	Invitation = Invitation.FromSchema(schema)
	M2mBlogPostTag = M2mBlogPostTag.FromSchema(schema)
	M2mUserRole = M2mUserRole.FromSchema(schema)
	OidcProvider = OidcProvider.FromSchema(schema)
	SysRole = SysRole.FromSchema(schema)
	SysSession = SysSession.FromSchema(schema)
	SysTenant = SysTenant.FromSchema(schema)
	SysUser = SysUser.FromSchema(schema)
	UserOidc = UserOidc.FromSchema(schema)
}
